#!/usr/bin/bash
#checks end of line

file_path=$1

if [[ -f "$file_path" ]]; then
    last_character=$(tail -c 1 "$file_path")
    if [[ $last_character != $'\n' ]]; then
        echo "File '$file_path' does not end with a new line."
        echo "" >> "$file_path"
        echo "Added a new line at the end of the file."
    fi
else
    echo "Invalid file path: $file_path"
fi
